version: '3.4'

services:
  mysql:
    image: mysql:8.0.26
    networks:
      - backend
    command: --default-authentication-plugin=mysql_native_password

  banking.operation.client.api:
    image: ${DOCKER_REGISTRY-}bankingoperationclientapi
    networks:
      - backend
    build:
      context: .
      dockerfile: Banking.Operation.Client.Api/Dockerfile
      
networks:
  backend:
    driver: bridge