version: '3.4'

services:
  mysql:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password

  banking.operation.client.api:
    image: ${DOCKER_REGISTRY-}bankingoperationclientapi
    build:
      context: .
      dockerfile: Banking.Operation.Client.Api/Dockerfile

volumes:
  mysql_data: